In [2]:
import pandas as pd
import numpy as np
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split

In [3]:
dataset = fetch_california_housing()

In [4]:
df = pd.DataFrame(data=dataset['data'],columns=dataset['feature_names'])
df.head()

   MedInc  HouseAge  AveRooms  ...  AveOccup  Latitude  Longitude
0  8.3252      41.0  6.984127  ...  2.555556     37.88    -122.23
1  8.3014      21.0  6.238137  ...  2.109842     37.86    -122.22
2  7.2574      52.0  8.288136  ...  2.802260     37.85    -122.24
3  5.6431      52.0  5.817352  ...  2.547945     37.85    -122.25
4  3.8462      52.0  6.281853  ...  2.181467     37.85    -122.25

[5 rows x 8 columns]

In [5]:
features = ['MedInc','HouseAge','AveRooms','AveBedrms','Population','AveOccup','Latitude','Longitude']

for feature in features:
    df[feature] = df[feature].replace(0,None)
    mean_value = np.mean(df[feature])
    df[feature] = df[feature].fillna(mean_value)

df.head()

   MedInc  HouseAge  AveRooms  ...  AveOccup  Latitude  Longitude
0  8.3252      41.0  6.984127  ...  2.555556     37.88    -122.23
1  8.3014      21.0  6.238137  ...  2.109842     37.86    -122.22
2  7.2574      52.0  8.288136  ...  2.802260     37.85    -122.24
3  5.6431      52.0  5.817352  ...  2.547945     37.85    -122.25
4  3.8462      52.0  6.281853  ...  2.181467     37.85    -122.25

[5 rows x 8 columns]

In [6]:
for feature in features:
    min_value = np.min(df[feature])
    max_value = np.max(df[feature])
    df[feature] = (df[feature] - min_value ) / (max_value - min_value)

df.head()

     MedInc  HouseAge  AveRooms  ...  AveOccup  Latitude  Longitude
0  0.539668  0.784314  0.043512  ...  0.001499  0.567481   0.211155
1  0.538027  0.392157  0.038224  ...  0.001141  0.565356   0.212151
2  0.466028  1.000000  0.052756  ...  0.001698  0.564293   0.210159
3  0.354699  1.000000  0.035241  ...  0.001493  0.564293   0.209163
4  0.230776  1.000000  0.038534  ...  0.001198  0.564293   0.209163

[5 rows x 8 columns]

In [7]:
X = df.iloc[:,:]
y = np.array(dataset['target'])

In [8]:
X_train , X_test , y_train , y_test = train_test_split(X,y,train_size=0.8,random_state=12)

In [9]:
def gradient(X,y,y_hat):
    grads = []
    for xi in X.T:
        grads.append(2 * np.mean(xi * (y_hat - y)))
    return np.array(grads)

In [10]:
def update(w,eta,grads):
    return w - (eta * grads)

In [11]:
def multi_variable_regression(X,w):
    return X @ w

In [12]:
def make_batches(X,y,batch_size):
    X_batches = []
    y_batches = []
    for i in range(0,len(X),batch_size):
        X_batches.append(X[i:i+batch_size])
        y_batches.append(y[i:i+batch_size])
    return np.array(X_batches),np.array(y_batches)

In [13]:
def loss_batch(y_batch,y_hat):
    return np.mean((y_batch - y_hat) **2)

In [14]:
m,n = X.shape
m,n

(20640, 8)

In [15]:
batch_size = 8
X_batches, y_batches = make_batches(X_train,y_train,batch_size)
X_batches.shape , y_batches.shape , X_train.shape, y_train.shape

((2064, 8, 8), (2064, 8), (16512, 8), (16512,))

In [16]:
16512 / 8

2064.0

In [24]:
epoches = 1000
eta = 0.1
w = np.random.randn(n)

for epoch in range(epoches):
    losses = []

    for (X_batch,y_batch) in zip(X_batches,y_batches):
        y_hat = multi_variable_regression(X_batch,w)
        loss = loss_batch(y_batch,y_hat)
        losses.append(loss)
        grads = gradient(X_batch,y_batch,y_hat)
        w = update(w,eta,grads)
    print(f'epoch : {epoch+1} mse: {np.mean(losses)}')

epoch : 1 mse: 0.6871201675244563
epoch : 2 mse: 0.6537407082187924
epoch : 3 mse: 0.6513804070355895
epoch : 4 mse: 0.6497125051563448
epoch : 5 mse: 0.6484523306744369
epoch : 6 mse: 0.6474416477819206
epoch : 7 mse: 0.6465893892062469
epoch : 8 mse: 0.6458413405937891
epoch : 9 mse: 0.645164225999846
epoch : 10 mse: 0.6445370768531565
epoch : 11 mse: 0.6439463857855495
epoch : 12 mse: 0.6433832900739112
epoch : 13 mse: 0.642841881362386
epoch : 14 mse: 0.6423181625618347
epoch : 15 mse: 0.6418093891602414
epoch : 16 mse: 0.6413136457022305
epoch : 17 mse: 0.6408295697400651
epoch : 18 mse: 0.6403561701024396
epoch : 19 mse: 0.639892706399572
epoch : 20 mse: 0.6394386087285453
epoch : 21 mse: 0.6389934239779332
epoch : 22 mse: 0.638556779828088
epoch : 23 mse: 0.638128360566008
epoch : 24 mse: 0.6377078908057373
epoch : 25 mse: 0.6372951245050218
epoch : 26 mse: 0.6368898375318467
epoch : 27 mse: 0.6364918226102422
epoch : 28 mse: 0.6361008858601563
epoch : 29 mse: 0.6357168444047673
epoch : 30 mse: 0.6353395246922428
epoch : 31 mse: 0.6349687612956189
epoch : 32 mse: 0.6346043960328343
epoch : 33 mse: 0.6342462773015504
epoch : 34 mse: 0.6338942595586501
epoch : 35 mse: 0.6335482028979007
epoch : 36 mse: 0.6332079726950243
epoch : 37 mse: 0.6328734392999031
epoch : 38 mse: 0.6325444777626127
epoch : 39 mse: 0.6322209675845589
epoch : 40 mse: 0.6319027924890283
epoch : 41 mse: 0.6315898402074156
epoch : 42 mse: 0.6312820022786785
epoch : 43 mse: 0.6309791738603797
epoch : 44 mse: 0.6306812535501928
epoch : 45 mse: 0.6303881432170773
epoch : 46 mse: 0.6300997478415157
epoch : 47 mse: 0.6298159753643318
epoch : 48 mse: 0.6295367365436735
epoch : 49 mse: 0.629261944819783
epoch : 50 mse: 0.6289915161872033
epoch : 51 mse: 0.6287253690740745
epoch : 52 mse: 0.6284634242281921
epoch : 53 mse: 0.6282056046094913
epoch : 54 mse: 0.6279518352886432
epoch : 55 mse: 0.6277020433514414
epoch : 56 mse: 0.6274561578086736
epoch : 57 mse: 0.6272141095111781
epoch : 58 mse: 0.626975831069793
epoch : 59 mse: 0.626741256779926
epoch : 60 mse: 0.6265103225504648
epoch : 61 mse: 0.6262829658367833
epoch : 62 mse: 0.6260591255775911
epoch : 63 mse: 0.6258387421353965
epoch : 64 mse: 0.6256217572403611
epoch : 65 mse: 0.6254081139373386
epoch : 66 mse: 0.6251977565358972
epoch : 67 mse: 0.6249906305631422
epoch : 68 mse: 0.6247866827191624
epoch : 69 mse: 0.6245858608349326
epoch : 70 mse: 0.6243881138325214
epoch : 71 mse: 0.6241933916874555
epoch : 72 mse: 0.6240016453931043
epoch : 73 mse: 0.6238128269269584
epoch : 74 mse: 0.6236268892186801
epoch : 75 mse: 0.6234437861198143
epoch : 76 mse: 0.6232634723750554
epoch : 77 mse: 0.6230859035949722
epoch : 78 mse: 0.6229110362300968
epoch : 79 mse: 0.6227388275462945
epoch : 80 mse: 0.6225692356013337
epoch : 81 mse: 0.622402219222578
epoch : 82 mse: 0.6222377379857369
epoch : 83 mse: 0.6220757521946024
epoch : 84 mse: 0.6219162228617165
epoch : 85 mse: 0.6217591116899093
epoch : 86 mse: 0.621604381054655
epoch : 87 mse: 0.6214519939871985
epoch : 88 mse: 0.6213019141584024
epoch : 89 mse: 0.621154105863275
epoch : 90 mse: 0.6210085340061351
epoch : 91 mse: 0.6208651640863805
epoch : 92 mse: 0.6207239621848205
epoch : 93 mse: 0.6205848949505423
epoch : 94 mse: 0.6204479295882797
epoch : 95 mse: 0.6203130338462555
epoch : 96 mse: 0.620180176004471
epoch : 97 mse: 0.620049324863417
epoch : 98 mse: 0.6199204497331842
epoch : 99 mse: 0.619793520422949
epoch : 100 mse: 0.6196685072308177
epoch : 101 mse: 0.6195453809340046
epoch : 102 mse: 0.6194241127793333
epoch : 103 mse: 0.6193046744740375
epoch : 104 mse: 0.6191870381768507
epoch : 105 mse: 0.6190711764893668
epoch : 106 mse: 0.6189570624476612
epoch : 107 mse: 0.6188446695141555
epoch : 108 mse: 0.6187339715697184
epoch : 109 mse: 0.6186249429059875
epoch : 110 mse: 0.6185175582179029
epoch : 111 mse: 0.6184117925964457
epoch : 112 mse: 0.6183076215215658
epoch : 113 mse: 0.6182050208552956
epoch : 114 mse: 0.6181039668350405
epoch : 115 mse: 0.6180044360670366
epoch : 116 mse: 0.6179064055199688
epoch : 117 mse: 0.6178098525187455
epoch : 118 mse: 0.6177147547384192
epoch : 119 mse: 0.6176210901982501
epoch : 120 mse: 0.6175288372559059
epoch : 121 mse: 0.6174379746017924
epoch : 122 mse: 0.61734848125351
epoch : 123 mse: 0.6172603365504323
epoch : 124 mse: 0.6171735201483999
epoch : 125 mse: 0.6170880120145288
epoch : 126 mse: 0.6170037924221267
epoch : 127 mse: 0.6169208419457122
epoch : 128 mse: 0.6168391414561395
epoch : 129 mse: 0.6167586721158169
epoch : 130 mse: 0.6166794153740224
epoch : 131 mse: 0.6166013529623109
epoch : 132 mse: 0.6165244668900094
epoch : 133 mse: 0.6164487394397994
epoch : 134 mse: 0.6163741531633822
epoch : 135 mse: 0.6163006908772254
epoch : 136 mse: 0.6162283356583887
epoch : 137 mse: 0.6161570708404266
epoch : 138 mse: 0.6160868800093637
epoch : 139 mse: 0.6160177469997453
epoch : 140 mse: 0.6159496558907559
epoch : 141 mse: 0.615882591002408
epoch : 142 mse: 0.6158165368917983
epoch : 143 mse: 0.6157514783494263
epoch : 144 mse: 0.615687400395581
epoch : 145 mse: 0.6156242882767855
epoch : 146 mse: 0.6155621274623049
epoch : 147 mse: 0.6155009036407125
epoch : 148 mse: 0.615440602716514
epoch : 149 mse: 0.6153812108068281
epoch : 150 mse: 0.6153227142381231
epoch : 151 mse: 0.6152650995430065
epoch : 152 mse: 0.615208353457068
epoch : 153 mse: 0.6151524629157757
epoch : 154 mse: 0.6150974150514199
epoch : 155 mse: 0.6150431971901099
epoch : 156 mse: 0.6149897968488176
epoch : 157 mse: 0.6149372017324687
epoch : 158 mse: 0.6148853997310822
epoch : 159 mse: 0.6148343789169536
epoch : 160 mse: 0.6147841275418845
epoch : 161 mse: 0.6147346340344566
epoch : 162 mse: 0.614685886997347
epoch : 163 mse: 0.6146378752046884
epoch : 164 mse: 0.6145905875994687
epoch : 165 mse: 0.6145440132909729
epoch : 166 mse: 0.6144981415522656
epoch : 167 mse: 0.6144529618177108
epoch : 168 mse: 0.6144084636805321
epoch : 169 mse: 0.6143646368904112
epoch : 170 mse: 0.6143214713511219
epoch : 171 mse: 0.6142789571182034
epoch : 172 mse: 0.6142370843966666
epoch : 173 mse: 0.6141958435387387
epoch : 174 mse: 0.6141552250416416
epoch : 175 mse: 0.6141152195454034
epoch : 176 mse: 0.6140758178307052
epoch : 177 mse: 0.6140370108167605
epoch : 178 mse: 0.6139987895592268
epoch : 179 mse: 0.6139611452481496
epoch : 180 mse: 0.6139240692059375
epoch : 181 mse: 0.6138875528853687
epoch : 182 mse: 0.6138515878676284
epoch : 183 mse: 0.6138161658603744
epoch : 184 mse: 0.6137812786958343
epoch : 185 mse: 0.6137469183289305
epoch : 186 mse: 0.6137130768354337
epoch : 187 mse: 0.6136797464101454
epoch : 188 mse: 0.6136469193651071
epoch : 189 mse: 0.6136145881278365
epoch : 190 mse: 0.6135827452395923
epoch : 191 mse: 0.613551383353663
epoch : 192 mse: 0.6135204952336827
epoch : 193 mse: 0.6134900737519728
epoch : 194 mse: 0.6134601118879089
epoch : 195 mse: 0.6134306027263099
epoch : 196 mse: 0.6134015394558564
epoch : 197 mse: 0.6133729153675275
epoch : 198 mse: 0.613344723853065
epoch : 199 mse: 0.6133169584034603
epoch : 200 mse: 0.613289612607462
epoch : 201 mse: 0.6132626801501081
epoch : 202 mse: 0.6132361548112807
epoch : 203 mse: 0.6132100304642799
epoch : 204 mse: 0.613184301074422
epoch : 205 mse: 0.6131589606976577
epoch : 206 mse: 0.6131340034792105
epoch : 207 mse: 0.6131094236522366
epoch : 208 mse: 0.613085215536505
epoch : 209 mse: 0.6130613735370959
epoch : 210 mse: 0.6130378921431213
epoch : 211 mse: 0.6130147659264631
epoch : 212 mse: 0.6129919895405297
epoch : 213 mse: 0.6129695577190333
epoch : 214 mse: 0.6129474652747834
epoch : 215 mse: 0.6129257070985006
epoch : 216 mse: 0.6129042781576463
epoch : 217 mse: 0.6128831734952711
epoch : 218 mse: 0.6128623882288806
epoch : 219 mse: 0.612841917549317
epoch : 220 mse: 0.6128217567196599
epoch : 221 mse: 0.6128019010741397
epoch : 222 mse: 0.6127823460170729
epoch : 223 mse: 0.612763087021808
epoch : 224 mse: 0.6127441196296897
epoch : 225 mse: 0.6127254394490396
epoch : 226 mse: 0.6127070421541497
epoch : 227 mse: 0.6126889234842935
epoch : 228 mse: 0.6126710792427503
epoch : 229 mse: 0.6126535052958443
epoch : 230 mse: 0.6126361975719993
epoch : 231 mse: 0.6126191520608064
epoch : 232 mse: 0.612602364812106
epoch : 233 mse: 0.612585831935084
epoch : 234 mse: 0.6125695495973804
epoch : 235 mse: 0.6125535140242139
epoch : 236 mse: 0.612537721497516
epoch : 237 mse: 0.6125221683550806
epoch : 238 mse: 0.6125068509897263
epoch : 239 mse: 0.6124917658484698
epoch : 240 mse: 0.6124769094317132
epoch : 241 mse: 0.612462278292443
epoch : 242 mse: 0.61244786903544
epoch : 243 mse: 0.6124336783165033
epoch : 244 mse: 0.6124197028416843
epoch : 245 mse: 0.6124059393665322
epoch : 246 mse: 0.6123923846953517
epoch : 247 mse: 0.6123790356804715
epoch : 248 mse: 0.6123658892215225
epoch : 249 mse: 0.6123529422647295
epoch : 250 mse: 0.6123401918022111
epoch : 251 mse: 0.6123276348712915
epoch : 252 mse: 0.6123152685538212
epoch : 253 mse: 0.6123030899755099
epoch : 254 mse: 0.6122910963052676
epoch : 255 mse: 0.6122792847545564
epoch : 256 mse: 0.6122676525767524
epoch : 257 mse: 0.6122561970665162
epoch : 258 mse: 0.6122449155591734
epoch : 259 mse: 0.6122338054301044
epoch : 260 mse: 0.6122228640941433
epoch : 261 mse: 0.6122120890049861
epoch : 262 mse: 0.6122014776546066
epoch : 263 mse: 0.6121910275726828
epoch : 264 mse: 0.6121807363260308
epoch : 265 mse: 0.6121706015180469
epoch : 266 mse: 0.6121606207881597
epoch : 267 mse: 0.612150791811288
epoch : 268 mse: 0.6121411122973094
epoch : 269 mse: 0.6121315799905345
epoch : 270 mse: 0.6121221926691908
epoch : 271 mse: 0.6121129481449138
epoch : 272 mse: 0.6121038442622445
epoch : 273 mse: 0.6120948788981367
epoch : 274 mse: 0.6120860499614701
epoch : 275 mse: 0.6120773553925708
epoch : 276 mse: 0.6120687931627395
epoch : 277 mse: 0.6120603612737867
epoch : 278 mse: 0.6120520577575745
epoch : 279 mse: 0.6120438806755659
epoch : 280 mse: 0.6120358281183801
epoch : 281 mse: 0.6120278982053545
epoch : 282 mse: 0.6120200890841146
epoch : 283 mse: 0.6120123989301487
epoch : 284 mse: 0.6120048259463897
epoch : 285 mse: 0.6119973683628028
epoch : 286 mse: 0.6119900244359808
epoch : 287 mse: 0.6119827924487429
epoch : 288 mse: 0.6119756707097421
epoch : 289 mse: 0.6119686575530768
epoch : 290 mse: 0.6119617513379091
epoch : 291 mse: 0.6119549504480881
epoch : 292 mse: 0.6119482532917802
epoch : 293 mse: 0.6119416583011024
epoch : 294 mse: 0.6119351639317642
epoch : 295 mse: 0.611928768662713
epoch : 296 mse: 0.6119224709957848
epoch : 297 mse: 0.6119162694553607
epoch : 298 mse: 0.611910162588029
epoch : 299 mse: 0.6119041489622508
epoch : 300 mse: 0.6118982271680319
epoch : 301 mse: 0.6118923958165998
epoch : 302 mse: 0.6118866535400848
epoch : 303 mse: 0.6118809989912053
epoch : 304 mse: 0.6118754308429603
epoch : 305 mse: 0.6118699477883228
epoch : 306 mse: 0.611864548539942
epoch : 307 mse: 0.6118592318298461
epoch : 308 mse: 0.6118539964091524
epoch : 309 mse: 0.6118488410477798
epoch : 310 mse: 0.611843764534167
epoch : 311 mse: 0.6118387656749945
epoch : 312 mse: 0.6118338432949098
epoch : 313 mse: 0.6118289962362582
epoch : 314 mse: 0.6118242233588176
epoch : 315 mse: 0.6118195235395353
epoch : 316 mse: 0.6118148956722708
epoch : 317 mse: 0.6118103386675422
epoch : 318 mse: 0.6118058514522752
epoch : 319 mse: 0.6118014329695574
epoch : 320 mse: 0.6117970821783945
epoch : 321 mse: 0.611792798053473
epoch : 322 mse: 0.6117885795849223
epoch : 323 mse: 0.6117844257780848
epoch : 324 mse: 0.6117803356532863
epoch : 325 mse: 0.6117763082456108
epoch : 326 mse: 0.6117723426046797
epoch : 327 mse: 0.6117684377944325
epoch : 328 mse: 0.611764592892912
epoch : 329 mse: 0.6117608069920525
epoch : 330 mse: 0.6117570791974714
epoch : 331 mse: 0.6117534086282626
epoch : 332 mse: 0.6117497944167953
epoch : 333 mse: 0.6117462357085139
epoch : 334 mse: 0.6117427316617415
epoch : 335 mse: 0.6117392814474863
epoch : 336 mse: 0.6117358842492514
epoch : 337 mse: 0.6117325392628468
epoch : 338 mse: 0.6117292456962045
epoch : 339 mse: 0.6117260027691963
epoch : 340 mse: 0.6117228097134546
epoch : 341 mse: 0.6117196657721953
epoch : 342 mse: 0.6117165702000441
epoch : 343 mse: 0.6117135222628649
epoch : 344 mse: 0.6117105212375903
epoch : 345 mse: 0.6117075664120567
epoch : 346 mse: 0.6117046570848389
epoch : 347 mse: 0.6117017925650898
epoch : 348 mse: 0.6116989721723805
epoch : 349 mse: 0.6116961952365443
epoch : 350 mse: 0.6116934610975228
epoch : 351 mse: 0.6116907691052126
epoch : 352 mse: 0.6116881186193174
epoch : 353 mse: 0.6116855090091989
epoch : 354 mse: 0.6116829396537335
epoch : 355 mse: 0.611680409941167
epoch : 356 mse: 0.6116779192689761
epoch : 357 mse: 0.6116754670437273
epoch : 358 mse: 0.6116730526809429
epoch : 359 mse: 0.611670675604963
epoch : 360 mse: 0.6116683352488167
epoch : 361 mse: 0.6116660310540883
epoch : 362 mse: 0.6116637624707907
epoch : 363 mse: 0.6116615289572371
epoch : 364 mse: 0.6116593299799178
epoch : 365 mse: 0.6116571650133761
epoch : 366 mse: 0.6116550335400871
epoch : 367 mse: 0.6116529350503398
epoch : 368 mse: 0.6116508690421182
epoch : 369 mse: 0.6116488350209858
epoch : 370 mse: 0.611646832499972
epoch : 371 mse: 0.6116448609994596
epoch : 372 mse: 0.6116429200470751
epoch : 373 mse: 0.6116410091775776
epoch : 374 mse: 0.6116391279327537
epoch : 375 mse: 0.6116372758613102
epoch : 376 mse: 0.611635452518772
epoch : 377 mse: 0.6116336574673774
epoch : 378 mse: 0.611631890275978
epoch : 379 mse: 0.6116301505199391
epoch : 380 mse: 0.6116284377810427
epoch : 381 mse: 0.611626751647389
epoch : 382 mse: 0.611625091713303
epoch : 383 mse: 0.6116234575792405
epoch : 384 mse: 0.611621848851695
epoch : 385 mse: 0.611620265143108
epoch : 386 mse: 0.6116187060717788
epoch : 387 mse: 0.6116171712617767
epoch : 388 mse: 0.6116156603428535
epoch : 389 mse: 0.6116141729503596
epoch : 390 mse: 0.6116127087251574
epoch : 391 mse: 0.6116112673135409
epoch : 392 mse: 0.6116098483671513
epoch : 393 mse: 0.6116084515428988
epoch : 394 mse: 0.6116070765028825
epoch : 395 mse: 0.6116057229143117
epoch : 396 mse: 0.6116043904494294
epoch : 397 mse: 0.6116030787854372
epoch : 398 mse: 0.6116017876044195
epoch : 399 mse: 0.6116005165932709
epoch : 400 mse: 0.6115992654436231
epoch : 401 mse: 0.6115980338517744
epoch : 402 mse: 0.6115968215186185
epoch : 403 mse: 0.6115956281495761
epoch : 404 mse: 0.6115944534545259
epoch : 405 mse: 0.6115932971477392
epoch : 406 mse: 0.6115921589478114
epoch : 407 mse: 0.6115910385775979
epoch : 408 mse: 0.6115899357641513
epoch : 409 mse: 0.6115888502386562
epoch : 410 mse: 0.6115877817363674
epoch : 411 mse: 0.6115867299965495
epoch : 412 mse: 0.6115856947624162
epoch : 413 mse: 0.6115846757810697
epoch : 414 mse: 0.6115836728034441
epoch : 415 mse: 0.6115826855842457
epoch : 416 mse: 0.6115817138818974
epoch : 417 mse: 0.6115807574584824
epoch : 418 mse: 0.6115798160796893
epoch : 419 mse: 0.6115788895147569
epoch : 420 mse: 0.6115779775364216
epoch : 421 mse: 0.611577079920865
epoch : 422 mse: 0.6115761964476603
epoch : 423 mse: 0.6115753268997229
epoch : 424 mse: 0.6115744710632602
epoch : 425 mse: 0.6115736287277198
epoch : 426 mse: 0.6115727996857432
epoch : 427 mse: 0.6115719837331159
epoch : 428 mse: 0.6115711806687214
epoch : 429 mse: 0.611570390294493
epoch : 430 mse: 0.6115696124153689
epoch : 431 mse: 0.6115688468392471
epoch : 432 mse: 0.6115680933769396
epoch : 433 mse: 0.6115673518421296
epoch : 434 mse: 0.6115666220513278
epoch : 435 mse: 0.6115659038238295
epoch : 436 mse: 0.6115651969816731
epoch : 437 mse: 0.6115645013495984
epoch : 438 mse: 0.6115638167550062
epoch : 439 mse: 0.6115631430279174
epoch : 440 mse: 0.6115624800009345
epoch : 441 mse: 0.6115618275092025
epoch : 442 mse: 0.6115611853903695
epoch : 443 mse: 0.6115605534845502
epoch : 444 mse: 0.611559931634288
epoch : 445 mse: 0.6115593196845188
epoch : 446 mse: 0.6115587174825343
epoch : 447 mse: 0.6115581248779471
epoch : 448 mse: 0.6115575417226552
epoch : 449 mse: 0.6115569678708085
epoch : 450 mse: 0.6115564031787727
epoch : 451 mse: 0.6115558475050982
epoch : 452 mse: 0.6115553007104859
epoch : 453 mse: 0.6115547626577553
epoch : 454 mse: 0.6115542332118115
epoch : 455 mse: 0.6115537122396151
epoch : 456 mse: 0.6115531996101501
epoch : 457 mse: 0.6115526951943943
epoch : 458 mse: 0.611552198865288
epoch : 459 mse: 0.6115517104977055
epoch : 460 mse: 0.6115512299684254
epoch : 461 mse: 0.611550757156102
epoch : 462 mse: 0.6115502919412364
epoch : 463 mse: 0.6115498342061501
epoch : 464 mse: 0.6115493838349548
epoch : 465 mse: 0.6115489407135289
epoch : 466 mse: 0.6115485047294882
epoch : 467 mse: 0.6115480757721601
epoch : 468 mse: 0.6115476537325584
epoch : 469 mse: 0.6115472385033578
epoch : 470 mse: 0.6115468299788684
epoch : 471 mse: 0.6115464280550107
epoch : 472 mse: 0.6115460326292919
epoch : 473 mse: 0.6115456436007823
epoch : 474 mse: 0.6115452608700902
epoch : 475 mse: 0.6115448843393401
epoch : 476 mse: 0.6115445139121489
epoch : 477 mse: 0.6115441494936042
epoch : 478 mse: 0.6115437909902409
epoch : 479 mse: 0.6115434383100206
epoch : 480 mse: 0.611543091362309
epoch : 481 mse: 0.6115427500578552
epoch : 482 mse: 0.6115424143087705
epoch : 483 mse: 0.6115420840285085
epoch : 484 mse: 0.6115417591318438
epoch : 485 mse: 0.6115414395348524
epoch : 486 mse: 0.6115411251548925
epoch : 487 mse: 0.6115408159105843
epoch : 488 mse: 0.6115405117217921
epoch : 489 mse: 0.6115402125096038
epoch : 490 mse: 0.611539918196314
epoch : 491 mse: 0.6115396287054045
epoch : 492 mse: 0.6115393439615272
epoch : 493 mse: 0.6115390638904861
epoch : 494 mse: 0.6115387884192196
epoch : 495 mse: 0.611538517475784
epoch : 496 mse: 0.611538250989336
epoch : 497 mse: 0.6115379888901158
epoch : 498 mse: 0.6115377311094315
epoch : 499 mse: 0.6115374775796427
epoch : 500 mse: 0.6115372282341441
epoch : 501 mse: 0.6115369830073499
epoch : 502 mse: 0.6115367418346795
epoch : 503 mse: 0.6115365046525404
epoch : 504 mse: 0.6115362713983147
epoch : 505 mse: 0.6115360420103441
epoch : 506 mse: 0.6115358164279147
epoch : 507 mse: 0.6115355945912431
epoch : 508 mse: 0.6115353764414624
epoch : 509 mse: 0.6115351619206087
epoch : 510 mse: 0.6115349509716067
epoch : 511 mse: 0.6115347435382558
epoch : 512 mse: 0.6115345395652181
epoch : 513 mse: 0.6115343389980054
epoch : 514 mse: 0.6115341417829642
epoch : 515 mse: 0.6115339478672662
epoch : 516 mse: 0.6115337571988927
epoch : 517 mse: 0.6115335697266246
epoch : 518 mse: 0.6115333854000288
epoch : 519 mse: 0.6115332041694476
epoch : 520 mse: 0.6115330259859856
epoch : 521 mse: 0.611532850801499
epoch : 522 mse: 0.611532678568584
epoch : 523 mse: 0.6115325092405656
epoch : 524 mse: 0.6115323427714867
epoch : 525 mse: 0.6115321791160959
epoch : 526 mse: 0.6115320182298396
epoch : 527 mse: 0.6115318600688483
epoch : 528 mse: 0.6115317045899283
epoch : 529 mse: 0.6115315517505506
epoch : 530 mse: 0.6115314015088407
epoch : 531 mse: 0.611531253823569
epoch : 532 mse: 0.6115311086541414
epoch : 533 mse: 0.611530965960589
epoch : 534 mse: 0.6115308257035582
epoch : 535 mse: 0.6115306878443024
epoch : 536 mse: 0.6115305523446728
epoch : 537 mse: 0.6115304191671078
epoch : 538 mse: 0.611530288274626
epoch : 539 mse: 0.6115301596308157
epoch : 540 mse: 0.611530033199828
epoch : 541 mse: 0.6115299089463663
epoch : 542 mse: 0.61152978683568
epoch : 543 mse: 0.6115296668335539
epoch : 544 mse: 0.6115295489063015
epoch : 545 mse: 0.6115294330207579
epoch : 546 mse: 0.6115293191442692
epoch : 547 mse: 0.6115292072446868
epoch : 548 mse: 0.6115290972903593
epoch : 549 mse: 0.6115289892501246
epoch : 550 mse: 0.6115288830933022
epoch : 551 mse: 0.611528778789687
epoch : 552 mse: 0.6115286763095409
epoch : 553 mse: 0.6115285756235863
epoch : 554 mse: 0.6115284767029985
epoch : 555 mse: 0.6115283795194
epoch : 556 mse: 0.6115282840448524
epoch : 557 mse: 0.6115281902518503
epoch : 558 mse: 0.6115280981133149
epoch : 559 mse: 0.6115280076025865
epoch : 560 mse: 0.6115279186934199

In [25]:
def mse_score(y_batch,y_hat):
    return np.mean((y_batch - y_hat) **2)

In [26]:
def mae_score(y_batch,y_hat):
    return np.mean(abs(y_batch - y_hat))

In [27]:
def r2_score(y_batch, y_hat):
    return 1 - sum((y_batch - y_hat) ** 2) / sum((y_batch - y_batch.mean()) ** 2)

In [67]:
batch_size = 32
X_batches, y_batches = make_batches(X_train,y_train,batch_size)
X_batches.shape , y_batches.shape , X_train.shape, y_train.shape
# w = np.random.randn(n)
w = [-1.8145861 ,  1.00559584, -0.34816822, -1.57737987, -1.42116979,
       -0.32263432, -1.10406993, -0.87049433]

epoches = 1000
eta = 0.1

main_mse_loss = []
main_mae_loss = []
main_r2_loss = []

for epoch in range(epoches):
    epoch_mse_loss = []
    epoch_mae_loss = []
    epoch_r2_loss = []

    for (X_batch,y_batch) in zip(X_batches,y_batches):

        y_hat = multi_variable_regression(X_batch,w)

        mse = mse_score(y_batch,y_hat)
        mae = mae_score(y_batch,y_hat)
        r2 = r2_score(y_batch,y_hat)

        epoch_mse_loss.append(mse)
        epoch_mae_loss.append(mae)
        epoch_r2_loss.append(r2)

        grads = gradient(X_batch,y_batch,y_hat)
        w = update(w,eta,grads)
    
    main_mse_loss.append(np.mean(epoch_mse_loss))
    main_mae_loss.append(np.mean(epoch_mae_loss))
    main_r2_loss.append(np.mean(epoch_r2_loss))

print(f"mse : {np.mean(main_mse_loss)}\nmae : {np.mean(main_mae_loss)}\nr2 : {np.mean(main_r2_loss)}")

mse : 0.6159482360265786
mae : 0.5733349052806338
r2 : 0.5086360341218085

In [73]:
y_hat = multi_variable_regression(X_test,w)
print(mse_score(y_test,y_hat))
print(r2_score(y_test,y_hat))

0.6047248782112478
0.5589734791428703