In [29]:
import pandas as pd
import numpy as np
from sklearn.datasets import fetch_california_housing

In [30]:
dataset = fetch_california_housing()

In [31]:
df = pd.DataFrame(data=dataset['data'],columns=dataset['feature_names'])
df.head()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25

In [32]:
features = ['MedInc','HouseAge','AveRooms','AveBedrms','Population','AveOccup','Latitude','Longitude']

for feature in features:
    df[feature] = df[feature].replace(0,None)
    mean_value = np.mean(df[feature])
    df[feature] = df[feature].fillna(mean_value)

df.head()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25

In [33]:
for feature in features:
    min_value = np.min(df[feature])
    max_value = np.max(df[feature])
    df[feature] = (df[feature] - min_value ) / (max_value - min_value)

df.head()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
0,0.539668,0.784314,0.043512,0.020469,0.008941,0.001499,0.567481,0.211155
1,0.538027,0.392157,0.038224,0.018929,0.067210,0.001141,0.565356,0.212151
2,0.466028,1.000000,0.052756,0.021940,0.013818,0.001698,0.564293,0.210159
3,0.354699,1.000000,0.035241,0.021929,0.015555,0.001493,0.564293,0.209163
4,0.230776,1.000000,0.038534,0.022166,0.015752,0.001198,0.564293,0.209163

In [47]:
X = df.iloc[:,:]
y = np.array(dataset['target'])

In [35]:
def gradient(X,y,y_hat):
    grads = []
    for xi in X.T:
        grads.append(2 * np.mean(xi * (y_hat - y)))
    return np.array(grads)

In [36]:
def update(w,eta,grads):
    return w - (eta * grads)

In [37]:
def multi_variable_regression(X,w):
    return X @ w

In [46]:
def make_batches(X,y,batch_size):
    X_batches = []
    y_batches = []
    for i in range(0,len(X),batch_size):
        X_batches.append(X[i:i+batch_size])
        y_batches.append(y[i:i+batch_size])
    return np.array(X_batches),np.array(y_batches)

In [39]:
def loss_batch(y_batch,y_hat):
    return np.mean((y_batch - y_hat) **2)

In [40]:
m,n = X.shape
m,n

(20640, 8)

In [48]:
batch_size = 8
X_batches, y_batches = make_batches(X,y,batch_size)
X_batches.shape , y_batches.shape , X.shape, y.shape

((2580, 8, 8), (2580, 8), (20640, 8), (20640,))

In [42]:
20640 / 8

2580.0

In [49]:
epoches = 100
eta = 0.1
w = np.random.randn(n)

for epoch in range(epoches):
    losses = []

    for (X_batch,y_batch) in zip(X_batches,y_batches):
        y_hat = multi_variable_regression(X_batch,w)
        loss = loss_batch(y_batch,y_hat)
        losses.append(loss)
        grads = gradient(X_batch,y_batch,y_hat)
        w = update(w,eta,grads)
    print(f'epoch : {epoch+1} mse: {np.mean(losses)}')

epoch : 1 mse: 0.41763153621528576
epoch : 2 mse: 0.3931163931177827
epoch : 3 mse: 0.3925106400945008
epoch : 4 mse: 0.3921082484586431
epoch : 5 mse: 0.39184134938460846
epoch : 6 mse: 0.391663379411549
epoch : 7 mse: 0.39154389809123746
epoch : 8 mse: 0.391462927072157
epoch : 9 mse: 0.39140733202936495
epoch : 10 mse: 0.3913684729491814
epoch : 11 mse: 0.3913406670797251
epoch : 12 mse: 0.39132017918996986
epoch : 13 mse: 0.3913045566437355
epoch : 14 mse: 0.39129219101983465
epoch : 15 mse: 0.39128202898585773
epoch : 16 mse: 0.39127338165060244
epoch : 17 mse: 0.39126579893678637
epoch : 18 mse: 0.39125898688760347
epoch : 19 mse: 0.3912527533141905
epoch : 20 mse: 0.3912469721388019
epoch : 21 mse: 0.39124156005896715
epoch : 22 mse: 0.3912364613208796
epoch : 23 mse: 0.3912316378209961
epoch : 24 mse: 0.3912270627011077
epoch : 25 mse: 0.39122271622778565
epoch : 26 mse: 0.39121858316055685
epoch : 27 mse: 0.3912146510861744
epoch : 28 mse: 0.39121090937646547
epoch : 29 mse: 0.39120734854592387
epoch : 30 mse: 0.3912039598633004
epoch : 31 mse: 0.3912007351227238
epoch : 32 mse: 0.39119766651348103
epoch : 33 mse: 0.39119474654952924
epoch : 34 mse: 0.39119196803408957
epoch : 35 mse: 0.3911893240439207
epoch : 36 mse: 0.3911868079238194
epoch : 37 mse: 0.39118441328569603
epoch : 38 mse: 0.39118213400897
epoch : 39 mse: 0.39117996424052515
epoch : 40 mse: 0.39117789839337863
epoch : 41 mse: 0.3911759311437521
epoch : 42 mse: 0.39117405742654593
epoch : 43 mse: 0.39117227242937685
epoch : 44 mse: 0.3911705715854096
epoch : 45 mse: 0.391168950565239
epoch : 46 mse: 0.39116740526806726
epoch : 47 mse: 0.3911659318123991
epoch : 48 mse: 0.3911645265264495
epoch : 49 mse: 0.39116318593842564
epoch : 50 mse: 0.39116190676681556
epoch : 51 mse: 0.3911606859107915
epoch : 52 mse: 0.3911595204408087
epoch : 53 mse: 0.39115840758946363
epoch : 54 mse: 0.3911573447426574
epoch : 55 mse: 0.3911563294310961
epoch : 56 mse: 0.3911553593221496
epoch : 57 mse: 0.3911544322120794
epoch : 58 mse: 0.3911535460186423
epoch : 59 mse: 0.39115269877406683
epoch : 60 mse: 0.39115188861839884
epoch : 61 mse: 0.3911511137932068
epoch : 62 mse: 0.39115037263563673
epoch : 63 mse: 0.3911496635728043
epoch : 64 mse: 0.391148985116509
epoch : 65 mse: 0.39114833585825837
epoch : 66 mse: 0.3911477144645863
epoch : 67 mse: 0.39114711967264965
epoch : 68 mse: 0.39114655028609113
epoch : 69 mse: 0.3911460051711511
epoch : 70 mse: 0.3911454832530169
epoch : 71 mse: 0.39114498351239424
epoch : 72 mse: 0.3911445049822883
epoch : 73 mse: 0.39114404674498304
epoch : 74 mse: 0.3911436079292042
epoch : 75 mse: 0.3911431877074585
epoch : 76 mse: 0.3911427852935348
epoch : 77 mse: 0.39114239994015915
epoch : 78 mse: 0.3911420309367933
epoch : 79 mse: 0.3911416776075684
epoch : 80 mse: 0.3911413393093447
epoch : 81 mse: 0.39114101542988966
epoch : 82 mse: 0.3911407053861665
epoch : 83 mse: 0.3911404086227279
epoch : 84 mse: 0.39114012461020486
epoch : 85 mse: 0.3911398528438886
epoch : 86 mse: 0.39113959284239636
epoch : 87 mse: 0.3911393441464181
epoch : 88 mse: 0.39113910631753757
epoch : 89 mse: 0.3911388789371231
epoch : 90 mse: 0.39113866160528493
epoch : 91 mse: 0.391138453939893
epoch : 92 mse: 0.3911382555756533
epoch : 93 mse: 0.3911380661632379
epoch : 94 mse: 0.3911378853684649
epoch : 95 mse: 0.39113771287152715
epoch : 96 mse: 0.3911375483662647
epoch : 97 mse: 0.3911373915594782
epoch : 98 mse: 0.3911372421702829
epoch : 99 mse: 0.3911370999294988
epoch : 100 mse: 0.3911369645790742